#!/usr/bin/env ruby

$LOAD_PATH << File.expand_path("..", __dir__)
$LOAD_PATH << File.expand_path("../lib", __dir__)

require "yaml"
require "lib/wpgsa"

uuid = ARGV[0]
abort("missing uuid") if !uuid || uuid.empty?

config_path = File.expand_path("../config.yaml", __dir__)
config = File.exist?(config_path) ? YAML.load_file(config_path) : {}
concurrency = Integer(config["max_concurrent_jobs"] || 2)

job = begin
  WPGSA::Job.load(uuid)
rescue WPGSA::InvalidDataId
  abort("invalid uuid")
end
job.run!(concurrency: concurrency)
